name: C/C++ CI

on:
  push:
    branches: [ "multicore" ]
  pull_request:
    branches: [ "multicore" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install GTest lib
        run:  sudo apt-get -y install libgtest-dev
      - name: Install OpenMP
        run: sudo apt-get -y install openmpi-common
      - name: Compiling files
        run: make all -f Makefile
      - name: Run testing
        run: ./TestKDTree
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            generadorKdTree
            queryKdTree
